# numpy
- ベクトルや行列など線形演算のライブラリ
- bool、int、float、complexもあるが標準のものと同じなので特に意識する必要はない
- Scipyの中に含まれる

In [2]:
import numpy as np

### 配列作成
- numpyではベクトルのように扱えるndarrayと行列のように扱えるmatrixの２つの型がある

### ndarray

#### array
- リストからndarrayを作る
- 引数は **(array_like, dtype=None)** 。dtypeは要素の型を指定。**int8(i1)、16(i2)、32(i4)、64(i8)、unit8(u1)、16(u2)、32(u4)、64(u8)、float16(f2)、32(f4)、64(f8)、128(f16)、complex64(c8)、128(c16)、256(c32)、bool(?)、unicode(U)、object(O)**。渡し方は**np.、文字列、コード**のどれか
- intは**int64**、floatは**float64**、strは**unicode**、unitは**unit64**
- インデックスをリストのように表記できる

In [3]:
x = np.array([[1,2,3], [4,5,6]], np.int32)
print(type(x))
print(x, x[0,0])

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]] 1


In [7]:
np.array([[1,2,3], [4,5,6]], 'int16')

array([[1, 2, 3],
       [4, 5, 6]], dtype=int16)

In [6]:
np.array([[1,2,3], [4,5,6]], float)

array([[1., 2., 3.],
       [4., 5., 6.]])

#### ※iinfo, finfo
- 数値の型の情報を得る
- int、unit、floatの値の範囲を表示
- max, minを適用できる

In [37]:
np.iinfo(np.int64)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [38]:
i64 = np.iinfo(np.int64)
i64.max

9223372036854775807

In [13]:
np.finfo(np.float64)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [14]:
np.iinfo(10) #整数はデフォルトでint64

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [16]:
np.finfo(10.0) #10だとエラー

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

### ※numpyで整数を作れる

In [98]:
np.int8(10)

10

In [101]:
np.int8(2**8+10)

10

#### asarray
- リストからndarrayを作る場合はarrayと同じ
- ndarrayを引数としたときに、arrayでは新しいインスタンスが生成され、asarrayでは参照コピーになる

In [77]:
x = np.asarray([[1,2,3], [4,5,6]], np.int32)
print(type(x))
print(x, x[0,0])

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]] 1


In [78]:
x = np.asarray([1,2,3])
a1 = np.array(x)
a2 = np.asarray(x)
x[0] = 0
print(a1, a2)

[1 2 3] [0 2 3]


### matrix
- リストからmatrixを作る

In [17]:
x = np.matrix([[1,2,3], [4,5,6]], np.int32)
print(type(x))
print(x, x[0,0])

<class 'numpy.matrix'>
[[1 2 3]
 [4 5 6]] 1


#### dtype, shape
- dtypeは要素の型、shapeはベクトルや行列の形を返す

In [18]:
x = np.array([[1,2,3], [4,5,6]])
y = np.matrix([[1,2,3], [4,5,6]])
print(x.dtype, x.shape)
print(y.dtype, y.shape)

int64 (2, 3)
int64 (2, 3)


In [ ]:
x = np.array([[1.0,2,3], [4,5,6]])  #小数の要素があるとfloatになる
print(x.dtype, x.shape)

float64 (2, 3)


**ベクトルと行列の違い**
- 2乗や\*がndarrayはアダマール積になり、matrixは内積（行列積）となる

In [22]:
array = np.array([[1, 2], [3, 4]])
mat = np.matrix([[1, 2], [3, 4]])
print(array**2)
print(mat**2)

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [34]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[1, 2], [3, 4]])
print(array1 * array2)

[[ 1  4]
 [ 9 16]]


In [40]:
mat1 = np.mat([[1, 2], [3, 4]])
mat2 = np.mat([[1, 2], [3, 4]])
print(mat1 * mat2)

[[ 7 10]
 [15 22]]


※arrayはnp.dotを使うことで内積が計算できる

In [33]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[1, 2], [3, 4]])
print(np.dot(array1, array2))

[[ 7 10]
 [15 22]]


※matrixはnp.multiplyを使うことでアダマール積が計算できる

In [42]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[1, 2], [3, 4]])
print(np.multiply(mat1, mat2))

[[ 1  4]
 [ 9 16]]


#### 単位行列(ndarry)

In [23]:
a = np.identity(3)
print(type(a))
print(a)

<class 'numpy.ndarray'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 1.1.4. zeros
- 全要素が0のndarrayを作る
- 引数は**(shape, dtype)**。shapeは1次元ならばint、多次元ならtuple

In [24]:
a = np.zeros(2)
print(type(a))
print(a)

<class 'numpy.ndarray'>
[0. 0.]


In [53]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


#### 1.1.5. ones
- 全要素が1

In [25]:
a = np.ones((2,2))
print(type(a))
print(a)

<class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]]


#### 1.1.6. full
- 任意の要素で埋めることができる

In [3]:
np.full((2, 3), 2)

array([[2, 2, 2],
       [2, 2, 2]])

### 配列の変形

- 転置

In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
a = np.mat([[1,2,3], [4,5,6], [7,8,9]])
a.T

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

- ベクトルや行列の形を変える

In [ ]:
x = np.array([[1,2,3], [4,5,6]])
y = np.matrix([[1,2,3], [4,5,6]])
print(x.reshape(-1))
print(y.reshape(-1))

[1 2 3 4 5 6]
[[1 2 3 4 5 6]]


### 配列の結合

#### concatenate
- 既存の軸で繋げる
- 引数でどの次元を繋げるか指定できる

In [23]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
np.concatenate([a1, a2])

array([1, 2, 3, 4, 5, 6])

In [21]:
a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[5, 6], [7, 8]])
np.concatenate([a1, a2], 0)  #0次元同士で結合

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [22]:
a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[5, 6], [7, 8]])
np.concatenate([a1, a2], 1)  #1次元同士で結合

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

#### block
- 引数の指定の仕方で結合できる

In [ ]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
np.block([a1, a2])

array([1, 2, 3, 4, 5, 6])

In [24]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
np.block([[a1], [a2]])

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[5, 6], [7, 8]])
np.block([a1, a2])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [26]:
a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[5, 6], [7, 8]])
np.block([[a1], [a2]])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

#### hstack
- 横につなげる

In [4]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
np.hstack([a1, a2])

array([1, 2, 3, 4, 5, 6])

In [13]:
a1 = np.mat([1, 2, 3])
a2 = np.mat([4, 5, 6])
np.hstack([a1, a2])

matrix([[1, 2, 3, 4, 5, 6]])

In [14]:
a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[5, 6], [7, 8]])
np.hstack([a1, a2])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

#### vstack
- 縦につなげる

In [11]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
np.vstack([a1, a2])

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[5, 6], [7, 8]])
np.vstack([a1, a2])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

#### dstack
- 深さ方向につなげる

In [ ]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
np.dstack([a1, a2])

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [27]:
a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[5, 6], [7, 8]])
np.dstack([a1, a2])   #同じ位置の要素同士がペア

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

### 配列の分割

### 配列の挿入

## 2. 演算

### 配列への演算
- ndarrayもmatrixも数値型との+、-、\*、/は各要素に演算される
- べき乗だけは注意

In [27]:
a = np.array([[0,1],[2,3]])
m = np.mat([[0,1],[2,3]])

In [28]:
print(a * 2)
print(m * 2)

[[0 2]
 [4 6]]
[[0 2]
 [4 6]]


In [29]:
print(a + 1)
print(m + 1)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


### 絶対値

In [ ]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7])
print(np.absolute(a))

[1.7 1.5 0.2 0.2 1.5 1.7]


### 三角関数
- sin、cos、tan、arcsin、arccos、arctanが使えて全要素に適用される
- radians、deg2rad(ラジアンから弧度法)、rad2deg(弧度法からラジアン)

In [21]:
x = np.array([0, 3.14/2])
np.sin(x)

array([0.        , 0.99999968])

### 指数、対数関数
- exp, log, log2, log10
- ネイピア数eはnp.eで定義されている
- sqrt

In [43]:
x = np.array([0, 1])
np.exp(x)

array([1.        , 2.71828183])

In [45]:
x = np.array([1, 2, 3])
np.log(x)

array([0.        , 0.69314718, 1.09861229])

In [46]:
x = np.array([1, 2, 3])
np.log2(x)

array([0.       , 1.       , 1.5849625])

### 複素数の演算

- 実部

In [48]:
a = np.array([1+1j, 1+2j, 1+3j])
np.real(a)

array([1., 1., 1.])

- 虚部

In [49]:
a = np.array([1+1j, 1+2j, 1+3j])
np.imag(a)

array([1., 2., 3.])

- 複素共役


In [47]:
a = np.array([1+1j, 1+2j, 1+3j])
np.conj(a)

array([1.-1.j, 1.-2.j, 1.-3.j])

### 小数の演算
- round(四捨五入)、trunc(切り捨て)、floor(切り捨て)、ceil(0への丸め)

In [30]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7])
print(np.round(a))  #偶数への丸め
print(np.trunc(a))  #絶対値を小さく
print(np.floor(a))  #切り捨て
print(np.ceil(a))  #切り上げ

[-2. -2. -0.  0.  2.  2.]
[-1. -1. -0.  0.  1.  1.]
[-2. -2. -1.  0.  1.  1.]
[-1. -1. -0.  1.  2.  2.]


### 統計量

- 最大・最小値

In [35]:
a = np.array([1, 9, -2, 4])
print(np.max(a), np.min(a))

9 -2


- 最大、最小値の行列を作る
- maximum、minimumはnanがあるところはnanになる
- fmax、fminはnanを無視する

In [ ]:
a = np.array([2, 4, 1, np.nan])
b = np.array([3, 2, 1, 0])
print(np.maximum(a, b))
print(np.minimum(a, b))
print(np.fmax(a, b))
print(np.fmin(a, b))

[ 3.  4.  1. nan]
[ 2.  2.  1. nan]
[3. 4. 1. 0.]
[2. 2. 1. 0.]


- 合計

In [89]:
a = np.array([[1,2,3,4,5]])
np.sum(a)

15

In [90]:
a = np.array([[1,2,3,4,5]])
a.sum()

15

In [93]:
a = np.array([[1,2,3],[4,5,6]])
a.sum(axis=1)

array([ 6, 15])

- 中央値

In [40]:
a = np.array([[1,2,3,4,5]])
np.median(a)

3.0

- 平均

In [39]:
a = np.array([[1,2,3,4,5]])
np.average(a)

3.0

- 分散

In [41]:
a = np.array([[1,2,3,4,5]])
np.var(a)

2.0

- 標準偏差

In [42]:
a = np.array([[1,2,3,4,5]])
np.std(a)

1.4142135623730951

### その他

- 重複の削除

In [ ]:
a = np.array([1, 9, -2, 4, 1])
np.unique(a)

array([-2,  1,  4,  9])

### 配列同士の演算

### アダマール積
- 要素どうしでの演算

In [32]:
a = np.array([0, 1, 2])
b = np.array([2, 4, 6])
np.multiply(a,b)

array([ 0,  4, 12])

In [33]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[1, 2], [3, 4]])
np.multiply(array1, array2)

array([[ 1,  4],
       [ 9, 16]])

### ドット積（内積）
- arrayでは1次元配列ではベクトルの内積、多次元配列では行列積となる

In [30]:
a = np.array([0, 1, 2])
b = np.array([2, 4, 6])
np.dot(a,b)

16

In [31]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[1, 2], [3, 4]])
np.dot(array1, array2)

array([[ 7, 10],
       [15, 22]])

### 外積

In [ ]:
a = np.array([0, 1, 2])
b = np.array([2, 4, 6])
print(np.outer(a,b))

[[ 0  0  0]
 [ 2  4  6]
 [ 4  8 12]]


In [44]:
a = np.mat([0, 1, 2])
b = np.mat([2, 4, 6])
print(np.outer(a,b))

[[ 0  0  0]
 [ 2  4  6]
 [ 4  8 12]]


### 共分散行列

In [28]:
a = np.array([0, 1, 2])
b = np.array([2, 4, 6])
np.cov(a,b)

array([[1., 2.],
       [2., 4.]])

In [80]:
a = np.mat([0, 1, 2])
b = np.mat([2, 4, 6])
np.cov(a,b)

array([[1., 2.],
       [2., 4.]])

In [76]:
a = np.array([[0, 1, 2], [2, 4, 6]])
np.cov(a1)

array([[0.5, 0.5],
       [0.5, 0.5]])

In [79]:
a = np.mat([[0, 1, 2], [2, 4, 6]])
np.cov(a1)

array(1.)

In [ ]:
a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[5, 6], [7, 8]])
np.cov(a1, a2)

array([[0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5]])

In [81]:
a1 = np.mat([[1, 2], [3, 4]])
a2 = np.mat([[5, 6], [7, 8]])
np.cov(a1, a2)

array([[0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5]])

## linalg
- 固有値や固有ベクトルに関する

In [83]:
import numpy.linalg as LA

In [87]:
a = np.array([1,2,3])
LA.norm(a)  #ノルム

3.7416573867739413

In [88]:
a = np.array([1,2,3])
LA.norm(a, ord=1)  #L1ノルム

6.0

In [ ]:
a = np.mat([1,2,3])
LA.norm(a)  #行列式

3.7416573867739413

In [38]:
a = np.mat([[1,2], [3,4]])
LA.det(a)  #行列式

-2.0000000000000004

In [33]:
a = np.mat([[1,2,3], [4,5,6], [7,8,9]])
LA.eig(a)  #固有値と固有ベクトル

(array([ 1.61168440e+01, -1.11684397e+00, -8.58274334e-16]),
 matrix([[-0.23197069, -0.78583024,  0.40824829],
         [-0.52532209, -0.08675134, -0.81649658],
         [-0.8186735 ,  0.61232756,  0.40824829]]))

In [35]:
a = np.mat([[1,2,3], [4,5,6], [7,8,9]])
LA.eigvals(a)  #固有値のみ

array([ 1.61168440e+01, -1.11684397e+00, -8.58274334e-16])

In [36]:
a = np.mat([[1,2,3], [4,5,6], [7,8,9]])
LA.inv(a)  #逆行列

matrix([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
        [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
        [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

## random
- 乱数の配列を作る

In [51]:
from numpy.random import *

- 標準正規分布

In [52]:
a = randn()
print(type(a), a)

<class 'float'> -0.8349163880878416


In [53]:
a = randn(10)
print(type(a), a)

<class 'numpy.ndarray'> [ 0.46549108 -0.39488183  0.20472138 -0.67842008 -1.12512664 -0.45494426
 -0.51847885  0.5261233  -0.16684888 -0.43070788]


In [59]:
a = randn(2, 2)
print(type(a), a)

<class 'numpy.ndarray'> [[-1.23361315  0.56538132]
 [-0.03201503 -0.52617059]]


- 正規分布

In [60]:
a = normal(10, 5)  #平均、分散の指定
print(type(a), a)

<class 'float'> 11.210505748599196


In [68]:
a = normal(10, 5, size=(10))
print(type(a), a)

<class 'numpy.ndarray'> [ 8.86967295  6.11478667 15.9777598   9.85004552  6.48430055  7.51916487
 14.61476078 10.93602056 11.32397722 15.21660865]


- 二項分布

In [64]:
a = binomial(10, 0.5, size=(10))
print(type(a), a)

<class 'numpy.ndarray'> [6 6 4 3 1 3 4 5 4 5]


- ポアソン分布

In [69]:
a = poisson(10, size=(10)) #λの指定
print(type(a), a)

<class 'numpy.ndarray'> [ 9  5 12  7 11 10 13 12 10  6]


- ベータ分布

In [71]:
a = beta(10, 5, size=(10)) #λの指定
print(type(a), a)

<class 'numpy.ndarray'> [0.76557709 0.70996351 0.66406561 0.53610088 0.28554051 0.82234787
 0.69005875 0.81792485 0.62735387 0.60314957]
